In [12]:
import glob
from PIL import Image
import numpy as np
from matplotlib.pyplot import imshow
from blend_modes import blending_functions
from scipy import misc

 
%matplotlib inline


def minMaxNormalize(img):
    z = img.max() - img.min()
    a = (img - img.min())/z
    return a * 255.0

def rgba2rgb( rgba, background=(255,255,255) ):
    row, col, ch = rgba.shape

    if ch == 3:
        return rgba

    assert ch == 4, 'RGBA image has 4 channels.'

    rgb = np.zeros( (row, col, 3), dtype='float32' )
    r, g, b, a = rgba[:,:,0], rgba[:,:,1], rgba[:,:,2], rgba[:,:,3]

    a = np.asarray( a, dtype='float32' ) / 255.0

    R, G, B = background

    rgb[:,:,0] = r * a + (1.0 - a) * R
    rgb[:,:,1] = g * a + (1.0 - a) * G
    rgb[:,:,2] = b * a + (1.0 - a) * B

    return np.asarray( rgb, dtype='uint8' )

In [13]:

masks = []
masksGrey = [] 


fileNames = []
for f in glob.iglob("mask/*"):
    fileNames.append(f.split("\\")[1])
                                    

for f in fileNames:
    path = 'mask\\'+f
    masksGrey.append(io.imread(path, as_gray=True))
    masks.append(np.asarray(Image.open(path), dtype=np.float64))

images = []
for f in fileNames:
    path = 'images\\'+f
    images.append( np.asarray(Image.open(path), dtype=np.float64 ))


    


In [14]:
from skimage import color
from skimage import io

for i in range(len(fileNames)):
    image = minMaxNormalize(images[i])
    H,W,C = image.shape
    mask = minMaxNormalize(masks[i])
    layer4 = minMaxNormalize(np.asarray(masksGrey[i]))
    rgba = np.concatenate((mask, layer4[:,:, np.newaxis]), axis=2)
    image1 = np.concatenate((image, np.ones((H,W, 1))), axis=2)
    res = blending_functions.screen( image1, rgba , 1.0)
    result  = res[:,:,0:3]
    name = fileNames[i].split(".")[0]
    misc.imsave( "mixed/" + name + "_1.jpg", result)





C:\Users\Amber\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: DeprecationWarning: `imsave` is deprecated!
`imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imwrite`` instead.
  


In [15]:
import os
for f in fileNames:
    path = 'mask\\'+f
    dst = 'mask\\' + f.split(".")[0] + "_1.jpg"
    os.rename(path, dst)

[[0.2        0.24210526 0.37894737 ... 0.23157895 0.6        0.16842105]
 [0.15789474 0.35789474 0.23157895 ... 0.43157895 0.38947368 0.12631579]
 [0.21052632 0.34736842 0.13684211 ... 0.55789474 0.2        0.08421053]
 ...
 [0.23157895 0.15789474 0.32631579 ... 0.17894737 0.13684211 0.35789474]
 [0.23157895 0.17894737 0.48421053 ... 0.09473684 0.22105263 0.31578947]
 [0.14736842 0.32631579 0.58947368 ... 0.11578947 0.35789474 0.18947368]]
